"""update type data id to String

Revision ID: 0834abd74b8a
Revises: 6c71135bd5b9
Create Date: 2023-11-24 13:49:54.692708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0834abd74b8a'
down_revision: Union[str, None] = '6c71135bd5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'password')
    # ### end Alembic commands ###
