"""update table

Revision ID: 1ba069cb6f48
Revises: 7518e739eece
Create Date: 2023-11-25 08:00:56.706525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba069cb6f48'
down_revision: Union[str, None] = '7518e739eece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voter', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voter', 'created_at')
    # ### end Alembic commands ###
