"""update table

Revision ID: 7518e739eece
Revises: ab5f298a691d
Create Date: 2023-11-25 07:58:46.198680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7518e739eece'
down_revision: Union[str, None] = 'ab5f298a691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voter', sa.Column('id_volunteer', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'voter', 'volunteer', ['id_volunteer'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voter', type_='foreignkey')
    op.drop_column('voter', 'id_volunteer')
    # ### end Alembic commands ###
